[package]
name = "features"
version = "0.1.0"
edition = "2021"

[dependencies]
cog_core = { path = "../../" }
crossterm = "0.28.1"
eyre = "0.6.12"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time"] }
