[package]
name = "cog_core"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
eyre = "0.6.12"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["rt"] }
